### ISSUE TITLE
Questions about the stddev computation

### ISSUE THREAD

**Issue by openaphid** [nikic/llvm-compile-time-tracker#1]
Is the stddev computed from the history data series? 

If yes, how do you get a stable benchmark result for each commit? Do you run it with extra warmup rounds?

**Comment by nikic** [comment]
> Is the stddev computed from the history data series

Yes, the stddev is computed from historical data, see https://github.com/nikic/llvm-compile-time-tracker/blob/a3f7d27f4cf47b8a5f0140cd6f8b63c81bb30a4e/compute_stddev.php#L94-L127.

> If yes, how do you get a stable benchmark result for each commit? Do you run it with extra warmup rounds?

No, everything is only run once. The two metrics I care about (instructions and max-rss) are sufficiently stable with a single run. (Sufficiently stable to detect 0.1% instructions regressions and 0.2% max-rss regressions.)
