### ISSUE TITLE
Site seems to be broken

### ISSUE THREAD

**Issue by AaronBallman** [nikic/llvm-compile-time-tracker#3]
Thank you for the incredibly helpful tool!

I went to the site to recommend someone add a branch to it for performance testing some of their change, and I noticed:
```
Argument 1 passed to groupByRemote() must be of the type array, null given, called in /var/www/llvm-compile-time-tracker/public/index.php on line 53
```
and it seems the rest of the page isn't loading:

![Capture](https://github.com/nikic/llvm-compile-time-tracker/assets/4587626/da678c24-bba9-4566-9eb4-57f127085602)

**Comment by nikic** [comment]
The server ran out of disk space again. I've mitigated the problem and the site should be back up.

I'm sure the day will come when I actually fix this, because it happens every few weeks at this point...
